### ISSUE TITLE
Method to byteArray

### ISSUE THREAD

**Issue by snatvb** [peterolson/BigInteger.js#103]
Do u have such method? Or how i can do it?

**Comment by peterolson** [comment]
You can convert a bigInt to hex, split it up into groups of two characters, and then create a byte array from that:

```
function toByteArray(x) {
    var hexString = x.toString(16);
    if(hexString.length % 2 > 0) hexString = "0" + hexString;
    var byteArray = [];
    for(var i = 0; i < hexString.length; i += 2) {
        byteArray.push(parseInt(hexString.slice(i, i + 2), 16));
    }
    return byteArray;
}
```

For example:

    toByteArray(bigInt("456742343535"))
    > [106, 87, 247, 19, 111]

**Comment by snatvb** [comment]
I'm so did it, thx, I was hoping on more fast resolve
(sry, what i not answered to you promptly)

**Comment by Zaliro** [comment]
Is there a "fromArray" alternative ?

**Comment by peterolson** [comment]
@Zaliro Sorry, I'm not sure I understand what you're asking?

**Comment by Zaliro** [comment]
It's ok i've found by myself ! Thanks for your quick answer.
