### ISSUE TITLE
Create bigInt from buffer/magnitude

### ISSUE THREAD

**Issue by cgebe** [peterolson/BigInteger.js#104]
Hey guys,

how can i achieve a similar result like BigInteger(int signum, byte[] magnitude) from Java.
https://docs.oracle.com/javase/7/docs/api/java/math/BigInteger.html

Is it achievable with `fromArray(digits, base = 10, isNegative?)`?

**Comment by peterolson** [comment]
Yes it is achievable with `fromArray`. Since there are 256 different possible bytes, you should pass in 256 for the base. Instead of passing 1, 0, or - 1 for the signum you can pass in `false` for positive and `true` for negative and whatever you like for zero.

**Comment by cgebe** [comment]
Thank you very much, got the expected result!
