### ISSUE TITLE
JSON Serialization / Deserialization

### ISSUE THREAD

**Issue by nanowizard** [peterolson/BigInteger.js#105]
First off, thanks for putting together this excellent library! It fit our needs perfectly.

I've recently encountered a situation where we'd like to store our `bigInt`s in JSON files and then retrieve them again at a later time. It seems odd to me that this library cannot reconstruct `bigInt`s from their default JSON-stringified value. Of course, it's possible to manually `toString()` all of the `bigInt` objects, which would make them compatible with the constructor when reading the data back. However, I think it would improve the library to do something like this automatically, perhaps by implementing the [`toJSON()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#toJSON()_behavior) method to transform the object into a readable input (such as a string). 

Another possibility is to add functionality to the constructor to be able to read in the serialized `bigInt` object, though it appears [that particular idea has already been proposed and denied](https://github.com/peterolson/BigInteger.js/issues/39). I suspect serializing to something like a string would be preferable anyway to reduce file size.

Again, I understand the user can take control of the serialization if needed, as they will have to take care of the deserialization bit to initialize the `bigInt`s again anyway. I just think it would make things easier on the user if the library already accounted for part of the process.

**Comment by peterolson** [comment]
Sorry for the delay. I've implemented the toJSON method as you suggested. Let me know if there's anything else you need.

**Comment by nanowizard** [comment]
Works wonderfully. Thanks!!!
