### ISSUE TITLE
Make available on cdnjs

### ISSUE THREAD

**Issue by htkoca** [peterolson/BigInteger.js#114]
I use this all the time, but I'd like to leverage cdnjs's cloudflare enabled CDN to serve this . Would it be possible to make this available - see https://cdnjs.com/libraries/biginteger

**Comment by peterolson** [comment]
[I've opened an issue on the cdnjs repository for this.](https://github.com/cdnjs/cdnjs/issues/12312)

**Comment by htkoca** [comment]
Thanks @peterolson , it's been added
