### ISSUE TITLE
Method - bitwise meaning

### ISSUE THREAD

**Issue by courteous** [peterolson/BigInteger.js#116]
can you please explain what this line exactly in the method bitwise is supposed to do?

 var sum = fn(xSign ? 1 : 0, ySign ? 1 : 0) !== 0 ? bigInt(-1) : bigInt(0);

thanks

**Comment by Yaffle** [comment]
sometimes, `-2**k` should be subtracted from the result to simulate 2s complement representation

**Comment by courteous** [comment]
thanks
