### ISSUE TITLE
Re: Apparent bug in BigInteger.js

### ISSUE THREAD

**Issue by WillamsAdrian** [peterolson/BigInteger.js#118]
Many thanks to Peter Olson for his work on BigInteger.js. 
I've discovered what looks like a bug. It'd be great if he could fix it as I don't have the confidence to delve into his code.

Attached is a screenshot of what I'm referring to. Examples 1,2 & 4 are giving the expected result, but not Example 3.

![biginteger js-bug](https://user-images.githubusercontent.com/35000283/34467403-4f5d615c-eef9-11e7-95ac-4af2c532f991.JPG)

**Comment by Yaffle** [comment]
```
var a = bigInt("1" + "0".repeat(20) + "2" + "0".repeat(15));
var b = bigInt("1" + "0".repeat(15));
var c = a.minus(b);
console.log(a.toString());
console.log(b.toString());
console.log(c.toString());
```
Cannot reproduce.
Could you provide the full code of your test?

**Comment by peterolson** [comment]
Is there a reason why you took a screenshot instead of copy and pasting the text directly? It is more difficult to reproduce from an image, especially when there are so many 0s in a row that it's easy to lose count.

Please provide the code demonstrating the bug in plain text.
