### ISSUE TITLE
bigInt('100000000000000008193').toJSNumber()

### ISSUE THREAD

**Issue by Yaffle** [peterolson/BigInteger.js#122]
`bigInt('100000000000000008193').toJSNumber()` returns different result in Edge/IE and other web browsers.
I have no use case, but seems, this should be documented or fixed.

The current implementation:
```
    BigInteger.prototype.valueOf = function () {
        return +this.toString();
    };
    BigInteger.prototype.toJSNumber = BigInteger.prototype.valueOf;
```

It seems, it will work better if to change it to:
```
    BigInteger.prototype.valueOf = function () {
        return parseInt(this.toString(), 10);
    };
    BigInteger.prototype.toJSNumber = BigInteger.prototype.valueOf;
```
Alghouth, even for `parseInt` the javascript specification - https://tc39.github.io/ecma262/#sec-parseint-string-radix - says "every significant digit after the 20th may be replaced by a 0 digit, at the option of the implementation" .

**Comment by peterolson** [comment]
If you use `parseInt` instead of the unary `+`, does it give consistent results across different browsers?

In any case, it seems implementation-dependent to me, but I'm fine with changing it to `parseInt` if in practice it makes it more consistent.

**Comment by Yaffle** [comment]
@peterolson,
yes, the results are conistent (I tested this case on IE8- IE11, Edge, Firefox 3.6+,Opera, Chrome, Safari, ...)
Although, the specification does not provide any guarantee

**Comment by peterolson** [comment]
OK, then that's fine with me. Feel free to make this change.
