### ISSUE TITLE
toArray

### ISSUE THREAD

**Issue by matthewleon** [peterolson/BigInteger.js#123]
I propose a `toArray` API as a dual of `fromArray`:

```
bigInt(x).toArray(base) => {isNegative: Bool, digits: Int[]}
```

**Comment by matthewleon** [comment]
(apologies for the ad hoc typing syntax above)

**Comment by peterolson** [comment]
Hi, looks like a good idea to me. 

I'm a little bit busy these days so it might be a little while before I get around to it, but in the meantime if you feel like adding this yourself I'd be happy to merge in your pull request.

**Comment by matthewleon** [comment]
I’ll be happy to write it.

**Comment by username1565** [comment]
I did this:
function to_base_array(n, base){
	var x = n;
		//console.log(x);
		var basearray = [];
		
		while(true){
			x = x.divmod(new BigInteger(base));
			basearray.unshift(x['remainder']['value']);
			x = x['quotient'];
			if(x['value']=='0'){break;}
		}
		//console.log(basearray);
		return basearray;
}

**Comment by username1565** [comment]
I did this:

function to_base_array(n, base){
	var x = n;
		//console.log(x);
		var basearray = [];
		
		while(true){
			x = x.divmod(new BigInteger(base));
			basearray.unshift(x['remainder']['value']);
			x = x['quotient'];
			if(x['value']=='0'){break;}
		}
		//console.log(basearray);
		return basearray;
}

and got basearray.
Then parse this and change cypher to symbols, like this:
else if(base==58){//set base58 alphabet
		alphabet = '123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';
		for(i=0;i<arr.length;i++){
			arr[i]=alphabet[arr[i]];
		}
		string = arr.join('');
	}

**Comment by peterolson** [comment]
This function has been added to the library already.
