### ISSUE TITLE
Is there a way to use mod and/or powmod so the remainder is positive?

### ISSUE THREAD

**Issue by irlnathan** [peterolson/BigInteger.js#126]
The native JavaScript modulo operator returns -5 for -12%7 and it looks like BigInteger does as well. I need the modulo operator to return a positive remainder as in -12 = 2(-7) + 2. Is there any way to do this using this library? Crossing fingers.

**Comment by peterolson** [comment]
Yes this is by design, the library tries to keep consistency with native JavaScript functionality.

You can get some positive number on your end by adding the modulo value if the result is negative.

**Comment by peterolson** [comment]
In your case, you would add 7 to the result: - 5 + 7 = 2
