### ISSUE TITLE
ModInv

### ISSUE THREAD

**Issue by username1565** [peterolson/BigInteger.js#129]
Fix this plz:

BigInteger.js
1. all 'BigInt(' -> replace to 'BigInteger(',
all 'BigInt.' -> replace to 'BigInteger('
I see you wanted to make this shorter, but this not working correctly.

2. replace BigInteger to Integer, not BigInteger. Because you have in code Integer.zero, Integer.one, etc...
BigInteger.prototype.modInv = function (n) {
        var t = Integer.zero, newT = Integer.one, r = parseValue(n), newR = this.abs(), q, lastT, lastR;
        while (!newR.equals(Integer.zero)) {

to do test this you can using this example:
>>> import gmpy
>>> gmpy.invert(1234567, 1000000007)
mpz(989145189)

abs1 = new BigInteger('1234567');
modulus = new BigInteger('1000000007');
document.write(
	'<br><br>modInv:'+
	'<br>'+abs1.toString()+
	" modInv "+modulus+
	'<br> = '+abs1.modInv(modulus)
);

3.     add new before BigInteger:
function toBase(n, base) {
        base = new BigInteger(base);

4. Also BigInteger.toString(2) not working. There is not working base array function,
and I used custom function, with byte array, like this:

<script language="JavaScript" type="text/javascript" src="BigInteger.js"></script>

<script>
function to_base_array(n, base){
	var x = n;
		//console.log(x);
		var basearray = [];
		
		while(true){
			x = x.divmod(new BigInteger(base));
			basearray.unshift(x['remainder']['value']);
			x = x['quotient'];
			if(x['value']=='0'){break;}
		}
		//console.log(basearray);
		return basearray;
}

function to_base_string(n, base){
	arr = to_base_array(n, base);
	//console.log(arr);
	if(base==2){
		string = arr.join('');
	}
	else if((base==8)||(base==16)){					//four bits
		for(i=0;i<arr.length;i++){
			arr[i]=arr[i].toString(base);
		}
		string = arr.join('');
	}
	else if(base==58){//set base58 alphabet
		alphabet = '123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';
		for(i=0;i<arr.length;i++){
			arr[i]=alphabet[arr[i]];
		}
		string = arr.join('');
	}
	else{console.log('incorrect base... ');}
	
	console.log(string);
	return string;
}

var bigint = new BigInteger('12445044073709801600');
//to_base_array(bigint, 16)
to_base_string(bigint, 2);			//1010110010110101101011011010010111111011100011011001000010000000
to_base_string(bigint, 16);			//ACB5ADA5FB8D9080
to_base_string(bigint, 58);			//VtW1qjsQxHm
/*
1010110010110101101011011010010111111011100011011001000010000000
acb5ada5fb8d9080
VtW1qjsQxHm
correct
*/

</script>

**Comment by username1565** [comment]
<script language="JavaScript" type="text/javascript" src="BigInteger.js"></script>

<script>
function to_base_array(n, base){
	var x = n;
		//console.log(x);
		var basearray = [];
		
		while(true){
			x = x.divmod(new BigInteger(base));
			basearray.unshift(x['remainder']['value']);
			x = x['quotient'];
			if(x['value']=='0'){break;}
		}
		//console.log(basearray);
		return basearray;
}

function to_base_string(n, base){
	arr = to_base_array(n, base);
	//console.log(arr);
	if(base==2){
		string = arr.join('');
	}
	else if((base==8)||(base==16)){					//four bits
		for(i=0;i<arr.length;i++){
			arr[i]=arr[i].toString(base);
		}
		string = arr.join('');
	}
	else if(base==58){//set base58 alphabet
		alphabet = '123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';
		for(i=0;i<arr.length;i++){
			arr[i]=alphabet[arr[i]];
		}
		string = arr.join('');
	}
	else{console.log('incorrect base... ');}
	
	console.log(string);
	return string;
}


var bigint = new BigInteger('12445044073709801600');
//to_base_array(bigint, 16)
to_base_string(bigint, 2);			//1010110010110101101011011010010111111011100011011001000010000000
to_base_string(bigint, 16);			//ACB5ADA5FB8D9080
to_base_string(bigint, 58);			//VtW1qjsQxHm
/*
1010110010110101101011011010010111111011100011011001000010000000
acb5ada5fb8d9080
VtW1qjsQxHm
correct
*/

</script>

**Comment by peterolson** [comment]
Sorry, I don't understand your question.

There is no `BigInteger` function in this library, only `bigInt`. `new BigInteger('1234567')` will throw an error because `BigInteger` is not defined.

I will not be renaming this function because that would break all of the code of people who use this library.

> Also BigInteger.toString(2) not working. 

The correct way to do this with this library is `bigInt(2).toString()`.

**Comment by username1565** [comment]
Thanks for your fix. I see now binary string is working.
```javascript
console.log(
	bigInt(-100500).toString(2) //-11000100010010100
);
```
