### ISSUE TITLE
BigInteger NOT

### ISSUE THREAD

**Issue by username1565** [peterolson/BigInteger.js#130]
abs1 = new bigInt('3712310970');			//to BigInteger
document.write(
	'<br><br>NOT:'+
	" "+abs1.toString()+
	' not = '+abs1.not()
);
//INCORRECT

/*
	3712310970 = 	11011101010001010101111010111010 bin
					00100010101110101010000101000101 NOT
					00100010101110101010000101000101 = 582656325 !==-3712310970
*/

I did used custom function to_base_array(n, base){ /*n to quotient after dividing n to base, and writing mod base^exp -array */} and this working, but how to make another bitwise operations correctly?
I see AND and OR is working. I'd write NOT using NOR biginteger
bitwise(this, this, function (a, b) { return ~(a | b); });
and this returns:
3712310970 not =-70372464877243

bitwise function...
result.push(fn(xDigit, yDigit));
console.log('NOR '+xDigit, yDigit); //<----- added
result: NOR 4546234 4161660 BigInteger.js:943

That's means something incorrect there...

**Comment by username1565** [comment]
I did negate function by division bigInt value 2 and save inverted remainders in bit string.
After this, according with bitstring length, multiply all bits to 2^position, and got inverted bigInt from string.

**Comment by Yaffle** [comment]
```
new bigInt('3712310970').not().toString()
// -> "-3712310971
```

**Comment by peterolson** [comment]
The `.not()` function is working as documented:

> Performs the bitwise NOT operation. The operands are treated as if they were represented using two's complement representation.

It is returning the same result as the `~` operator in Javascript:

    bigInt(1).not() // -2
    bigInt(-2).not() // 1
    bigInt(123).not() // -124
    bigInt(-124).not() // 123
    ~1 // -2
    ~-2  // 1
    ~123 // -124
    ~-124 // 123

I will not change the behavior of the `.not()` function because 1) it is working as documented and 2) doing so would be a breaking change in the library and could cause existing code to stop working.

As a side note, there's no reason to use `new` when creating a bigInt. You can just write `bigInt(2)`.

**Comment by username1565** [comment]
test message

**Comment by username1565** [comment]
Yeap, you are right. This integers are different because different ranges
of negative integers for converting this to positive numbers.
bigInt(1).not() // -2
bigInt(-2).not() // 1
but see this in details:
1 byte: ~00000001 = 11111110 (-2) = 254
2 bytes: ~00000000 00000001 = 11111111 11111110 (-2) = 65534

So I did write modified code, where I can specify bits.
and this, can be not function.
```javascript
  BigInteger.prototype.someNot = function (bits) {//default - undefined
    var bits = (typeof bits === 'undefined') ? false : bits; //if undefined - false, else use this bits
    var negated = this.negate().prev();
    if(bits===false){//if false - return negated
        return negated;	//return (0-N)-1
    }else{
    //if bits was been specified
      if(this.isNegative()){
        return negated = this.abs().subtract(bigInt(1));  //-1 -(-n) = |n| - 1 
      }
      else{
      //2^bits-1 (bits number of one bits)
      var ones = bigInt(1).shiftLeft(bits).subtract(bigInt(1));
      return negated = ones.subtract(this.divmod(bigInt(1).shiftLeft(bits))['remainder']);
      }
    }
};
  SmallInteger.prototype.someNot = BigInteger.prototype.someNot;
```


test code
```javascript
console.log(
	'bits not specified\n'
	+'~1 = '+bigInt('1').someNot().toString()+'\n'
	+'~-2 = '+bigInt('-2').someNot().toString()+'\n'
	+'~123 = '+bigInt('123').someNot().toString()+'\n'
	+'~-124 = '+bigInt('-124').someNot().toString()+'\n'
	+'~3712310970 = '+bigInt('3712310970').someNot().toString()+'\n'
	+'~582656325 = '+bigInt('582656325').someNot().toString()+'\n\n'

	+'32 bits specified \n'
	+'~1 = '+bigInt('1').someNot(32).toString()+'\n'
	+'~4294967294 = '+bigInt('4294967294').someNot(32).toString()+'\n'
	+'~-2 = '+bigInt('-2').someNot(32).toString()+'\n'
	+'~1 = '+bigInt('1').someNot(32).toString()+' = (-2)+2^32\n'
	+'~123 = '+bigInt('123').someNot(32).toString()+' = (-124)+2^32\n'
	+'~4294967172 = '+bigInt('4294967172').someNot(32).toString()+'\n'
	+'~-124 = '+bigInt('-124').someNot(32).toString()+'\n'
	+'~3712310970 = '+bigInt('3712310970').someNot(32).toString()+'\n'
	+'~582656325 = '+bigInt('582656325').someNot(32).toString()+'\n'
	
	+'\n\n 8 bits specified \n'
	+'~1 = '+bigInt('1').someNot(8).toString()+'\n'
	+'~4294967294 = '+bigInt('4294967294').someNot(8).toString()+'. 4294967294%(2^8) = 254 and ~254 = 1 (~11111110 = 00000001 = 1)\n'
	+'~-2 = '+bigInt('-2').someNot(8).toString()+'. -2 = 254 (- 256)\n'
	+'~1 = '+bigInt('1').someNot(8).toString()+' = (-2)+2^8\n'
	+'~254 = '+bigInt('254').someNot(8).toString()+'\n'
	+'~123 = '+bigInt('123').someNot(8).toString()+'\n'
	+'~132 = '+bigInt('132').someNot(8).toString()+'\n'
	+'~4294967172 = '+bigInt('4294967172').someNot(8).toString()+'\n'
	+'~-124 = '+bigInt('-124').someNot(8).toString()+'\n'
	+'~3712310970 = '+bigInt('3712310970').someNot(8).toString()+' 3712310970%(2^8) = 186. ~186(~10111010) = 01000101(69)\n'
	+'~582656325 = '+bigInt('582656325').someNot(8).toString()+' 582656325%(2^8) = 69. ~69(~01000101) = 186(10111010)\n'
);
```
result:
```javascript
bits not specified
~1 = -2
~-2 = 1
~123 = -124
~-124 = 123
~3712310970 = -3712310971
~582656325 = -582656326

32 bits specified 
~1 = 4294967294
~4294967294 = 1
~-2 = 1
~1 = 4294967294 = (-2)+2^32
~123 = 4294967172 = (-124)+2^32
~4294967172 = 123
~-124 = 123
~3712310970 = 582656325
~582656325 = 3712310970


 8 bits specified 
~1 = 254
~4294967294 = 1. 4294967294%(2^8) = 254 and ~254 = 1 (~11111110 = 00000001 = 1)
~-2 = 1. -2 = 254 (- 256)
~1 = 254 = (-2)+2^8
~254 = 1
~123 = 132
~132 = 123
~4294967172 = 123
~-124 = 123
~3712310970 = 69 3712310970%(2^8) = 186. ~186(~10111010) = 01000101(69)
~582656325 = 186 582656325%(2^8) = 69. ~69(~01000101) = 186(10111010)
```
