### ISSUE TITLE
probably prime test

### ISSUE THREAD

**Issue by username1565** [peterolson/BigInteger.js#131]
Hello. I see your biginteger using Fermat Test for test big primes.
Can you add Miller-Rabin algo in your bigInt class, like this:
https://gist.github.com/bnlucas/5857478

This is effective primality test, error is 1/(N^k), where N - number for test, k - number of rounds.
20 rounds is the best.

P.S.: Sorry, I don't know how to post code here...

**Comment by peterolson** [comment]
If you add a pull request for this feature I will consider adding it.

**Comment by username1565** [comment]
Ok. This https://codepen.io/anon/pen/VxdvjO is updated. There is modified NOT and working Miller-Rabin primality test algo. You can test this. I'll add pool request now.
