### ISSUE TITLE
Development and fix bugs

### ISSUE THREAD

**Issue by username1565** [peterolson/BigInteger.js#132]
I think this thread can be main here.
1. First that I want to offer, that adding:
var bigInt = BigInteger = (function (undefined) {
in the beginning for old BigInteger users.
In this case
var big = new BigInteger('100500');
will be working.
2. You can add Miller-Rabin primality test, for working with bigInt
3. You can add NOR and fix NOT bitwise functions. See previous threads with me.
https://github.com/peterolson/BigInteger.js/issues/131
https://github.com/peterolson/BigInteger.js/issues/130

I did test all functions and your last version have good conversations to basestring and basearray.
Many bugs is fixed. Best regards.

**Comment by username1565** [comment]
https://codepen.io/anon/pen/VxdvjO here is JS code with NOT function fixed.
All is commented + tabulations saved.

**Comment by username1565** [comment]
Miller-Rabin JS implementation for BigInteger added to previous code.
You can test this and update your code.
Have a nice day.

**Comment by username1565** [comment]
Miller-Rabin algo fixed and updated. Test generator added.

**Comment by peterolson** [comment]
1. I don't see a good reason to change the name of the function. Adding a `BigInteger` alias would pollute the namespace, and it's a best practice for libraries to only add one name to the global namespace. Renaming from `bigInt` to `BigInteger` would break existing code.

2.  In principle I'm not opposed to adding the Miller-Rabin test, but `isProbablePrime` is already one of the lesser-used functions in this library and I feel like adding more functions similar to it will add bloat to the code that most users will not need.

3. See my comments in #130 

In the future if you want to propose code changes to the library, I would recommend creating pull requests for them - one for each proposed change.

**Comment by username1565** [comment]
1. OK.
2. OK, but I leave this here, and Miller-Rabin is already working and tested.
3. I did write small NOT function without any changes for previous calls,
and this could not cause existing code to stop working, if (bits) is undefined.

I don't understand how to using pool request here, but I like to test your library and have propositions.
