### ISSUE TITLE
Symbolic encode for BigInteger

### ISSUE THREAD

**Issue by username1565** [peterolson/BigInteger.js#134]
Hello, Peter Olson.
I did write modified bigInt with supporting encoding for BigIntegers using alphabet and UNICODE symbols. You can see this here: https://github.com/username1565/BigInteger/commit/58de5fefde2d2830de0a77eddafad5b6e51da595 and compare files, to see changes.
Test page available here: https://github.com/username1565/BigInteger/blob/master/test_encoding_and_decoding.html
Now, BigInteger size is 172KB, but this can be lesser if spaces replace to Tab.

Also, I did add cube root calculating algorithm in separate page, here: https://github.com/username1565/BigInteger/blob/master/cube_root.html
You can play with it in your spare time.

**Comment by peterolson** [comment]
Sorry, this change more than triples the size of the library. I don't think this will be used be enough users to justify that amount of bloat.

**Comment by username1565** [comment]
Ok, I'll delete this from pull request and you can find all changes on my page:
https://github.com/username1565/BigInteger.js
Maybe you can do yourself symbolic encoding and decoding BigIntegers with lower file size,
of couse - if you interested this.
Also you can update BigRat.

Have a nice day.
