### ISSUE TITLE
Plans for the tc39 bigint proposal?

### ISSUE THREAD

**Issue by xuset** [peterolson/BigInteger.js#136]
Awesome project! I just found out that a [new standard](https://www.chromestatus.com/feature/5371603852460032) is being pushed forward for arbitrary sized integers and seems to have some partial support in chrome, firefox, and safari. I'm curious what this means for this project since it seems that this project could benefit greatly from the [performance improvements](https://developers.google.com/web/updates/2018/05/bigint).

Happy coding!

**Comment by peterolson** [comment]
Yes, good point. 

My plan would be to make BigInteger.js work sort of as a polyfill: check if the environment supports native bigints, if so, the library will be a thin wrapper over the native implementation. Otherwise, fall back to the library's current implementation.

**Comment by username1565** [comment]
Just leave here USER-SCRIPTS for all this browsers. And JavaScript is programming language for userscripts.

**Comment by fiery-** [comment]
Chrome 67 already supports BigInt and there is a new [JSBI](https://github.com/GoogleChromeLabs/jsbi) polyfill for other browsers. I'm sure that BigInteger.js will get real boost from the native Chrome's implementation.

**Comment by peterolson** [comment]
Resolved. BigInteger.js now works as a polyfill for the native BigInt.

**Comment by zgayjjf** [comment]
This is a breaking change, you should update your major or minor version, instead of just updating patch version.

**Comment by peterolson** [comment]
Could you clarify why it is a breaking change? What previously-functioning code is this change breaking?
