### ISSUE TITLE
Negative mod

### ISSUE THREAD

**Issue by wa1one** [peterolson/BigInteger.js#139]
bigInt('-17').mod(bigInt('5'))

Should be 3

**Comment by wa1one** [comment]
How to change mod function to my own mod function

**Comment by peterolson** [comment]
It works as expected. BigInteger matches the behavior of plain JavaScript in this case:

```
-17 % 5 === -2
```

**Comment by peterolson** [comment]
If you want to have the positive mod, you can add 5 to the result.
