### ISSUE TITLE
Why it is still SmallInteger ?

### ISSUE THREAD

**Issue by ying2025** [peterolson/BigInteger.js#141]
![image](https://user-images.githubusercontent.com/28092539/41326456-a46c5946-6ef1-11e8-9249-6d22cf0f22c1.png)
var bigInterger = require("big-integer");  // 引入大整型
![image](https://user-images.githubusercontent.com/28092539/41326466-aea8f338-6ef1-11e8-9a9d-5df9e13cb55d.png)

**Comment by ying2025** [comment]
![image](https://user-images.githubusercontent.com/28092539/41339495-896d0286-6f27-11e8-90e1-315d92653437.png)

![image](https://user-images.githubusercontent.com/28092539/41339470-7ae325f6-6f27-11e8-87f2-56cba8380194.png)

**Comment by peterolson** [comment]
Sorry, I do not understand you questions. Please improve your questions:

- Please do not paste code in images. Use plain text instead.
- Please paste all of the code used to generate the output.
- Please specify what the expected output is, and how it differs from the actual output.
