### ISSUE TITLE
Get the value of bigInt

### ISSUE THREAD

**Issue by ying2025** [peterolson/BigInteger.js#142]
I want get the value of bigInt type data, and copy it to a array. But I fail it.
![image](https://user-images.githubusercontent.com/28092539/41347942-bd88ec9a-6f3d-11e8-86c3-e1f9bba02784.png)

```
{ [Number: 5.0349076016023663e+306]
  value: 
   [ 2186985,
     659745,
     2288479,
     9725085,
     4995649,
     8181855,
     3824696,
     1661436,
     1029112,
     7703133,
     2570164,
     685584,
     4128790,
     3969081,
     7912760,
     9669147,
     3655019,
     5323483,
     2679775,
     7163979,
     6173533,
     8131390,
     3901880,
     3239679,
     3711540,
     9421076,
     719181,
     4126526,
     8361433,
     5001754,
     5461351,
     9366786,
     8830717,
     7832649,
     639130,
     4323733,
     5778043,
     8620616,
     2941434,
     5671445,
     3965424,
     3664128,
     7601602,
     503490 ],
  sign: false,
  isSmall: false }
```

**Comment by peterolson** [comment]
Sorry, I do not understand you questions. Please improve your questions:

- Please do not paste code in images. Use plain text instead.
- Please paste all of the code used to generate the output.
- Please specify what the expected output is, and how it differs from the actual output.
