### ISSUE TITLE
some edge cases for `shiftRight` and `shiftLeft`

### ISSUE THREAD

**Issue by Yaffle** [peterolson/BigInteger.js#143]
Is it possible to change the behavior of shiftRightand shiftLeft to match how BigInt works (https://github.com/tc39/proposal-bigint) with large second argument?

`bigInt(0).shiftRight(-100000000000000000000)` should give `bigInt(0)`
`bigInt(0).shiftLeft(100000000000000000000)` should give `bigInt(0)`
`bigInt(5).shiftRight(100000000000000000000)` should give `bigInt(0)`
`bigInt(5).shiftLeft(-100000000000000000000)` should give `bigInt(0)`
`bigInt(-5).shiftRight(100000000000000000000)` should give `bigInt(-1)`
`bigInt(-5).shiftLeft(-100000000000000000000)` should give `bigInt(-1)`

**Comment by peterolson** [comment]
I'm looking at the [specification](https://tc39.github.io/proposal-bigint/) for it, and I can't find this behavior documented anywhere. Am I missing it somewhere?

I'm curious why they would want to return `0` and `1` for large arguments? Do you have any idea?

**Comment by Yaffle** [comment]
just because the operation "a << b" works only when both args are bigints (as all other Arithmetic and Bitwise operations).

**Comment by Yaffle** [comment]
what if to update the limit to 9007199254740991 ?
