### ISSUE TITLE
Enhancement. Fast mulmod method

### ISSUE THREAD

**Issue by username1565** [peterolson/BigInteger.js#148]
Hello, Peter Olson!
Can you add in your free time, fast multiply mod method, **aka Montgomery trick**:
https://en.wikipedia.org/wiki/Montgomery_modular_multiplication

You can see source code here:
https://github.com/indutny/bn.js/blob/master/lib/bn.js
function BN.mont() and rewrite this for your bigInt-library.

**Comment by username1565** [comment]
Also, this is available, here, in the peercoin paperwallet:
https://github.com/Elbandi/peercoin-walletgenerator/blob/master/src/biginteger.js

**Comment by gardhr** [comment]
You're overoptimizing. 

![screenshot from 2018-07-09 05-33-00](https://user-images.githubusercontent.com/24468810/42445895-21be416e-833a-11e8-8680-09ca33f1a316.png)

Just need a faster machine!

**Comment by username1565** [comment]
What do you mean in picture?
Mulmod is not multiple or square. This is multiple and mod.
As you can see by last link at line 1179, there is many functions:
```javascript
//1. Montgomery reduction
function Montgomery(m){}
//2. xR mod m
Montgomery.prototype.convert = function (x) {}
//3. x/R mod m
Montgomery.prototype.revert = function (x) {
//4. x = x/R mod m (HAC 14.32)
Montgomery.prototype.reduce = function (x) {}
//5. r = "xy/R mod m"; x,y != r
Montgomery.prototype.mulTo = function (x, y, r) {}
//r = "x^2/R mod m"; x != r
Montgomery.prototype.sqrTo = function (x, r) {}
```
Also, you can see there **Barrett modular reduction**, _(at line 1241)_
and **Modular reduction using "classic" algorithm**, _(at line 1164)_

**Comment by peterolson** [comment]
BigInteger.js is not designed to be a fully-featured number theory library. A very small percentage of the users of this library would ever us a mulMod function, so I probably won't be adding this.
