### ISSUE TITLE
Wrong output on and()

### ISSUE THREAD

**Issue by idofilus** [peterolson/BigInteger.js#153]
On chrome you can find the correct way:
`6827581190108759180n & 0xfn` _===_ `12n`

On bigInt:
`bigInt(6827581190108759180).and(0xf).value` _===_ `8`

Seems like with few examples I tried, it always off by 4, but not 100% sure about it.

**Comment by Yaffle** [comment]
@idofilus  try
`bigInt('6827581190108759180').and(0xf).value === 8`

**Comment by idofilus** [comment]
@Yaffle Not sure I understand what you mean by 

> `6827581190108759180` equals `6827581190108759040`

_6827581190108759180_ = 1011110110000000111000011101011000101111001001001000100 **10001100**
_6827581190108759040_ = 1011110110000000111000011101011000101111001001001000100 **00000000**

Now if we will use the lowest bits that are different:
```
   10001100
&      1111
 ----------
       1100
```

**Comment by Yaffle** [comment]
@idofilus , in javascript the numbers are stored using the "double-precision floating point format" and so have 53 bits of precision,  your source code will parsed and the value will be rounded.

**Comment by idofilus** [comment]
@Yaffle I understand, but it seems like V8 is emulating it as a even bigger than _unsigned long long_ ?

For example, if you would try to increment with the max of Unsigned long long:
`18446744073709551615 + 1 === 18446744073709552000`

Values are rounded

But, using _V8's BigInt_ it would be possible:
`18446744073709551615n + 1n === 18446744073709551616n`

Even: 
`18446744073709551615n * -1n - 10n === -18446744073709551625n`

So, even tho your point is logical. It seems like _BigInt_ is much bigger than this.

**Comment by Yaffle** [comment]
@idofilus , I agree. `BigInt` is much bigger. The expression `bigInt(6827581190108759180)`  will be evaluated as a function call with number value, not BigInt value.

**Comment by idofilus** [comment]
@Yaffle I used BN.js to solve my case, they are using strings as input to probably overcome the issue you described. I guess this is the nature of this current library because of it. Maybe consider having to support as a string as well with unlimited number range ? Or at least let people know about limitation :)
I mean, not sure if it's already mentioned here. But I'm doing pretty standard thing here _(kind of)_ using the server with _uint64_t_ and handling modification to number on the client side as well.
