### ISSUE TITLE
Optimization question

### ISSUE THREAD

**Issue by gardhr** [peterolson/BigInteger.js#157]
I noticed a few instances in the codebase where equals(Integer[0]) and equals(Integer[1]) are used. Maybe just an over-optimization but wouldn't it be more efficient to use isZero() and isUnit() in those cases?

**Comment by peterolson** [comment]
Yes, it would be slightly faster and cleaner.

**Comment by gardhr** [comment]
Really interesting thing though is that, even so, this library actually runs blazingly fast!

**Comment by peterolson** [comment]
I've made some performance benchmarks comparing this library to other big integer libraries:

http://peterolson.github.io/BigInteger.js/benchmark/

I'd certainly pull in commits changing instances of `equals(Integer[0])`, although I doubt there would be any noticeable differences in performance overall. There are probably some bigger bottlenecks in the library.

**Comment by gardhr** [comment]
Nah, too much stochastic noise from the random sampling to tell. None of the instances seemed to be performance-critical anyway.
