### ISSUE TITLE
Improve the use of forced eval

### ISSUE THREAD

**Issue by ty-everett** [peterolson/BigInteger.js#165]
The library uses eval when using native implementation because ** is syntax error, but when we are forced to use eval the best way is to use it in a non-polluting way.

What I mean is that when this is used with rollup it makes it impossible to use some efficiencies

https://rollupjs.org/guide/en#avoiding-eval

Where eval is used, we should use this instead:

```
let globalEval = eval;
globalEval("(a,b)=>a**b");
```

Let me know any thoughts on this

**Comment by peterolson** [comment]
This should already be taken care of, since eval is only executed once to create the `pow` function.

See commit 2ca52567ae34e0f0d869cb10c78d234afa344cb5
