### ISSUE TITLE
Omitting leading zeros when splitting segments from string

### ISSUE THREAD

**Issue by jaredgorski** [peterolson/BigInteger.js#174]
I'm trying to use `bigInt` to parse a big integer back and forth from being a string, but a zero is being lost.

<img width="607" alt="screen shot 2019-03-04 at 3 42 54 pm" src="https://user-images.githubusercontent.com/36674760/53770635-bdafae80-3e94-11e9-8564-6ff5f82cb71a.png">

**Comment by peterolson** [comment]
You're directly trying to parse the `value` property? It's only used internally.

I don't see any issue happening with `toString`:

```
var x = "1551726003360588900"
bigInt(x).toString() === x // true
```

**Comment by jaredgorski** [comment]
Ah, thanks for checking. I'll make sure. Closing for now
