### ISSUE TITLE
Typescript: toString must have 2 params

### ISSUE THREAD

**Issue by pashinin** [peterolson/BigInteger.js#175]
https://github.com/peterolson/BigInteger.js/blob/bf283df222ec54ec464a82234a26947f679edaac/BigInteger.d.ts#L362

Actually toString() method accepts second param - alphabet.
But Typescript linter gives an error now if given 2 arguments:

```
Expected 0-1 arguments, but got 2.
```

**Comment by pashinin** [comment]
https://github.com/peterolson/BigInteger.js/pull/176

**Comment by peterolson** [comment]
Thanks for pointing that out! I merged your pull request.
