### ISSUE TITLE
Works fine in Google chrome but not in IE,Microsoft Edge.

### ISSUE THREAD

**Issue by husainsr** [peterolson/BigInteger.js#182]
I had wrote `let a = long('140627929000000122')['value']`;
works fine in Google chrome but in IE/Microsoft Edge i got comma separated value
like [146, 2792900, 4406]

**Comment by Yaffle** [comment]
`value` is an internal property, it contains the native BigInt in browsers, that support it, and array in other browsers

**Comment by husainsr** [comment]
It is compatible with IE/Microsoft Edge ?

**Comment by husainsr** [comment]
![ie](https://user-images.githubusercontent.com/29568758/57283147-1afdf100-70cc-11e9-8406-4c207c6cdc91.PNG)
How would i get value from this.

**Comment by husainsr** [comment]
Can anyone please answer me for the same.

**Comment by Yaffle** [comment]
@husainsr , what is the question?
Google Chrome has BigInt support, so this library uses the native BigInt internally.
Edge does not support BigInt, so this library uses the array internally. So you will not be able to get the BigInt value in current version of Edge.

**Comment by husainsr** [comment]
Sorry this is not a feasible solution.
