### ISSUE TITLE
Endianness flag for toArray

### ISSUE THREAD

**Issue by s1na** [peterolson/BigInteger.js#183]
Hello,

[We](github.com/ethereumjs) rely heavily on big numbers and are [discussing](https://github.com/ethereumjs/fixed-bn.js/issues/9) switching to a library that polyfills to native BigInts, and that's how I found your great library.

Internally we mostly use big endian representation and If I'm not mistaken the `toArray` (and `fromArray`) methods work with little endian representation. I was wondering if you'd consider adding a flag for this to the relevant methods (or would accept a PR doing this).

Thanks

**Comment by peterolson** [comment]
Wouldn't it be pretty simple to just call `.reverse()` on the arrays? IMHO that would be a more readable way to change the order than passing in an extra boolean argument to the `toArray`/`fromArray` functions.

**Comment by s1na** [comment]
Sorry, I mistakenly got that impression from #39 (`Note that the array representation is small endian`).
