### ISSUE TITLE
How to get value of Integer object?

### ISSUE THREAD

**Issue by babuhacker** [peterolson/BigInteger.js#187]
code:>>>>>>>>>>>>>>>>>>>>>>>>

var bigInt = require("big-integer");
let e=65537;
let n=667;
let m = 18;
function enc(m, n, e) {
	let c =  bigInt(m).modPow(e, n);
	console.log(c);
};
enc(m,n,e);

code:>>>>>>>>>>>>>>>>>>>>>>

output>>>>>>>>>>>>>>>>>>>>>>>
       Integer { value: 55n }
output>>>>>>>>>>>>>>>>>>>>>>>

sir, I want output 55. but i am getting Integer { value: 55n }.
what should i add some code to get output 55. 

expected Output>>>>>>>>>>>>>>>>>>>
       55
expected Output>>>>>>>>>>>>>>>>>>>

**Comment by peterolson** [comment]
Just do `c.toString()`

**Comment by babuhacker** [comment]
thanx
