### ISSUE TITLE
Error in the versioning of the package updates

### ISSUE THREAD

**Issue by jlobo** [peterolson/BigInteger.js#189]
Hello guys, first, thanks for the great work with the library, it’s really useful to me.

Secondly, I published a package on npm with `big-integer` as a dependency and it worked very well until someone told me it was falling. I realize that the bitLength() method used to return a number and now returns a `BigInt` and that breaks everything.

When I check, the version that is being installed now of the big-integer package is `1.6.44`, and I was working with `1.6.36`. then, the library changes the signature of the API but that is not reflected in the package version.

Keep that in mind for the next update guys.

**Comment by peterolson** [comment]
Thanks for the note. I'll go ahead and close this issue since there's not really any action that can be taken on it at this point.
