### ISSUE TITLE
How convert bigint to string?

### ISSUE THREAD

**Issue by uxitten** [peterolson/BigInteger.js#196]
```bigInteger(123456789012345678).toString()```

Result:

```123456789012345680```

**Comment by Happypig375** [comment]
JavaScript number precision issues.
Use `bigInteger('123456789012345678').toString()`.

**Comment by uxitten** [comment]
@Happypig375 Thank's, but this is a sample and i received that from server
```
bigInteger(num).toString() // result 123456789012345680
```
So, I can't convert to string that because this issue stay:

```
bigInteger(String(num)).toString() //result 123456789012345680
```

**Comment by Happypig375** [comment]
You are using native JavaScript numbers.
```js
String(num) // 123456789012345680
123456789012345678 == 123456789012345680 // true
```

**Comment by uxitten** [comment]
@Happypig375 All right, but I need it. 

```js
function mask(number){
   ....
}

const number = 123456789012345678 // get from server
const maskedNumber = mask(number);
//result is '123-45-6789-012345680'
```
But, I need this result '123-45-6789-012345678'

**Comment by Yaffle** [comment]
@uxitten , get the string from the server

**Comment by uxitten** [comment]
Suppose I can't.  No way?

**Comment by Yaffle** [comment]
@uxitten , a lot of ways:
1) you know, that the value can be stored as binary64 exactly, and so the conversion back to decimal is exact, in this case use `number.toFixed(0)`;
2) parse the output from the server in a way, that the value will not be converted to number (don't call  JSON.parse(...) directly)

**Comment by Yaffle** [comment]
Why can't you get it as string from the server? Cannot you modify the receiving code?

**Comment by uxitten** [comment]
Thanks, man, it's ok
