### ISSUE TITLE
In node.j my number has commas

### ISSUE THREAD

**Issue by benzmuircroft** [peterolson/BigInteger.js#204]
In the browser

    console.log(bigInt('9999999999999999990').add('1').value.toString());

    9999999999999999991

In Node.js

    console.log(bigInt('9999999999999999990').add('1').value.toString());

    9999991,9999999,99999

**Comment by Happypig375** [comment]
`value` is the internal representation. Browsers that implement bigInt will have a native value. In contrast, when bigInt is not natively implemented, an array is used to polyfill. This behavior is expected.

**Comment by benzmuircroft** [comment]
so i should `value.reverse().join('')`

?

**Comment by Happypig375** [comment]
Use `toString()` without `.value`

**Comment by benzmuircroft** [comment]
k thanks
