### ISSUE TITLE
bigInt(long hexstring) throws an "Invalid integer error"

### ISSUE THREAD

**Issue by wanseob** [peterolson/BigInteger.js#205]
Bug reproduction
```
$ node
> bigInt = require('big-integer')
> bigInt('0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa')
Thrown:
Error: Invalid integer: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    at parseStringValue (~/node_modules/big-integer/BigInteger.js:1382:29)
    at parseValue (~/node_modules/big-integer/BigInteger.js:1413:20)
    at Integer (~/node_modules/big-integer/BigInteger.js:15:16)
```

**Comment by wanseob** [comment]
Current node version is v12.16.2

**Comment by peterolson** [comment]
`bigInt` doesn't use the `0x` prefix for hex numbers. You can pass `16` as a second argument to specify that the input is hex:

    bigInt('aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 16)

**Comment by wanseob** [comment]
Thank you it helped. FYI, it also worked for a short length '0x' prefixed hex like bigInt('0xaaaa') thou I was confused.

**Comment by wanseob** [comment]
Tested again, but it still has a problem. I'm using node v10.
Here's the log.
```
> bigInt('aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa')
Thrown:
Error: Invalid integer: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    at parseStringValue (/home/wanseob/Projects/wanseob/zkopru/node_modules/big-integer/BigInteger.js:1382:29)
    at parseValue (/home/wanseob/Projects/wanseob/zkopru/node_modules/big-integer/BigInteger.js:1413:20)
    at Integer (/home/wanseob/Projects/wanseob/zkopru/node_modules/big-integer/BigInteger.js:15:16)

```

**Comment by peterolson** [comment]
Did you forget the second argument? You didn't pass in `16`

**Comment by wanseob** [comment]
Oo yes you're right, apologize my silly mistake

**Comment by gre** [comment]
the problem is that it seems to work in the V8 implementation so you might want to reconsider supporting the '0xfffff' syntax. this lib can't act as polyfill because of this.

(left is node, right is this library)

![Capture d’écran 2020-12-10 à 21 12 34](https://user-images.githubusercontent.com/211411/101824419-77d54f00-3b2c-11eb-8d2e-9fd792610e6d.png)


or maybe don't state in the Readme it is a polyfill.

**Comment by peterolson** [comment]
There was no intention to the exact API of native BigInt. This library was created before native BigInt was proposed, and contains features that native BigInt does not have, so doing so would introduce breaking changes.

What the readme means is that this library will work as expected whether or not the environment it runs on supports native BigInt. If there is no support, it will use an array-of-numbers implementation. If BigInt is supported, then this library will take advantage of it.
