### ISSUE TITLE
BigInt constructor

### ISSUE THREAD

**Issue by omatrot** [peterolson/BigInteger.js#207]
I know that bigInt is a function, but I would need to wrap it into something that could allow me to  use bigInt with a constructor:
>new (...args: any[]): any

How can I do that, knowing that I'm using TypeScript?

**Comment by peterolson** [comment]
Of course you can always create a constructor function wrapper:

```
function BigInteger(...args) {
    return bigInt(...args);
}
```

Then you can use `new`:

```
let x  = new BigInteger("hello", 36)
```

I'm not sure why exactly you would need to do this, though.

**Comment by omatrot** [comment]
Thanks for the input, I need this to use it in conjunction with a serialization library that uses [annotations](https://github.com/Diademe/dcerialize#annotations).
