### ISSUE TITLE
Works very slow on Microsoft Edge non chromium versions

### ISSUE THREAD

**Issue by elorzafe** [peterolson/BigInteger.js#208]
Thanks for this @peterolson 

I am testing this library on Microsoft Edge version 44.x version and is very slow compared to Google Chrome (on the same machine for the same operation)

Benchmark:
Google Chrome: 100ms average
Microsoft Edge: 70,000ms average

**Comment by Yaffle** [comment]
It seems, other libs may work a little faster, although, still 10 or more times slower, then native BigInt...
Some other libs also have optimized versions of "modPow"

**Comment by elorzafe** [comment]
Do you some examples?

**Comment by Yaffle** [comment]
@elorzafe , the fastest in Edge library is https://github.com/chromium/octane/blob/master/crypto.js

**Comment by elorzafe** [comment]
@Yaffle thanks! I tried that implementation, the problem on Edge is bnModPow operation. For large numbers like the one I mention on the description on the issue it takes around 16,000ms

**Comment by MendelssohnTW** [comment]
Hello. Excellent tool.  One suggestion: Remove the small arrays.  Use only arrays.  This will bring you better performance.  In Python the same functions are executed 300 times faster than in Javascript.  You can improve performance by using string arrays and not subdivide types.

**Comment by Yaffle** [comment]
@elorzafe , Have you tried with DevTools closed? For me, when the DevTools are opened it is very slow, otherwise it takes 150ms with jsbn.

@MendelssohnTW , I don't believe string arrays faster than digit arrays and type subdivision affects performance so much, there should be something else.

**Comment by MendelssohnTW** [comment]
@peterolson. 
With bit strings you will need only one loading and unloading operation into memory.  You will use more memory in exchange for performance.  
Using the give string, you don't need to subdivide for binary calculations.  Just one process for all sizes.  least one identification operation.  
The binary calculation algorithms you already have.  
Do a little test with strings and do with matrices.  Memory access is for each index in the array.  In the case of the string, access is unique.  For a 512-bit array you will have 512 memory accesses.  For the string you will only have one load access for the same 512 bits.  Take a test.

**Comment by MendelssohnTW** [comment]
@peterolson. 
I'm saying this, because I used your module to try to decrypt an HMAC and it took 6 hours.  I used a python module and it took 3 minutes.  I used your calculations and modified the inputs and outputs without conversions and it took 1 hour and 30 min.  I used only powmod, mod, multiply and divide.

**Comment by MendelssohnTW** [comment]
Here is the code using your module.

https://github.com/MendelssohnTW/AES-in-CBC-CTR-mode/blob/master/colision.js

**Comment by MendelssohnTW** [comment]
The same code using Python

https://github.com/MendelssohnTW/AES-in-CBC-CTR-mode/blob/master/discrete_log.py

**Comment by elorzafe** [comment]
> @elorzafe , Have you tried with DevTools closed? For me, when the DevTools are opened it is very slow, otherwise it takes 150ms with jsbn.
> 
> @MendelssohnTW , I don't believe string arrays faster than digit arrays and type subdivision affects performance so much, there should be something else.

Yes I did, same result :(
