### ISSUE TITLE
Repo Benchmark page not working

### ISSUE THREAD

**Issue by joananespina** [peterolson/BigInteger.js#209]
Just reporting that the repo benchmark page ([http://peterolson.github.io/BigInteger.js/benchmark/](http://peterolson.github.io/BigInteger.js/benchmark/)) is not working.

It looks like it is stuck in: `Please wait for libraries to load... 6/7`

I don't know if it is related, but the console is throwing an `Uncaught null` error in the **testWorker.js** file.

**Comment by peterolson** [comment]
Fixed.
