### ISSUE TITLE
NativeBigInt

### ISSUE THREAD

**Issue by username1565** [peterolson/BigInteger.js#212]
Hello. I see you added the supporting for NativeBigInt.
I want to say, you, this is supporting `.toString()` method,
```JavaScript
console.log(new bigInt(100500n.toString())); //BigInt-object
```
and old bigInt object was working good.

To return a native BigInt, there is enough to make
```JavaScript
console.log(eval(new bigInt('100500').toString()+'n')); //100500n
```
Maybe, you can minify bigint library, using this.

Also, I see a some bug, and maybe, you can fix it: 
```JavaScript
console.log(new bigInt(1005000000000000000000000).toString()); //---> "1004999999999999964348416"
```

Best regards.

**Comment by peterolson** [comment]
The problem is that you should put the number inside a string, like this:

    console.log(new bigInt("1005000000000000000000000").toString()); //---> "1005000000000000000000000"

This is because 1005000000000000000000000 is too large to preserve precision as a native JavaScript number.

**Comment by username1565** [comment]
Look at this:
```javascript
new bigInt('1005010000000000000000').prev().toString('1005010000000000000000') //"<1.00501e+21>"
```

**Comment by peterolson** [comment]
By design bases that are too large are not supported.

**Comment by username1565** [comment]
Ok. Look at this
https://github.com/peterolson/BigInteger.js/blob/2c922709216d64b499bee1eda3172c3bb1b8fca8/BigInteger.js#L1192

this always true, because:
```
var x = undefined;
console.log(!x); //true;
```
so
```
(ceseSencetive !== undefined && !caseSencetive)
```
or just `(caseSencetive==!1)` will works, there.
