### ISSUE TITLE
CWE-77: Improper Neutralization of Special Elements used in a Command ('Command Injection')

### ISSUE THREAD

**Issue by love89music** [peterolson/BigInteger.js#218]
Hi team,

Will we have plan to fix this in the future. 
https://ossindex.sonatype.org/vulnerability/afbfcdda-fd2d-42b6-aa10-bf8343466d99?component-type=npm&component-name=big-integer

Thank you

**Comment by attritionorg** [comment]
https://github.com/peterolson/BigInteger.js/issues/216

**Comment by love89music** [comment]
Hi Team,

If team can specify the lodash version to "lodash": "^4.17.21" we can fix current issue.

Thanks.

**Comment by peterolson** [comment]
Fixed by #219
