### ISSUE TITLE
bigInt.randBetween issue

### ISSUE THREAD

**Issue by thearthouse** [peterolson/BigInteger.js#221]
why it's never hit a number 33185509 when using bigInt.randBetween("16777216", "33554431");

**Comment by Yaffle** [comment]
looks like it will never be bigger 26777215 (which is 10**7 + 16777216 - 1)

**Comment by thearthouse** [comment]
> looks like it will never be bigger 26777215 (which is 10**7 + 16777216 - 1) only when BigInt is supported

also tested bigInt.randBetween(BigInt("16777216"), BigInt("33554431"));
result is same

**Comment by Yaffle** [comment]
seems,
https://github.com/peterolson/BigInteger.js/blob/master/BigInteger.js#L1181
this line should have digits[i] + 1

**Comment by thearthouse** [comment]
> seems, https://github.com/peterolson/BigInteger.js/blob/master/BigInteger.js#L1181 this line should have digits[i] + 1:
> 
> ```diff
> -            var top = restricted ? digits[i] : BASE;
> +           var top = restricted ? digits[i] + 1 : BASE;
> ```

i change that and its working fine , will be there any problem on high integers like 2**120

**Comment by Yaffle** [comment]
ok

**Comment by Yaffle** [comment]
@peterolson a test is falling and I don't know how to resolve it :-)

**Comment by peterolson** [comment]
Which test?

**Comment by Yaffle** [comment]
@peterolson see https://github.com/peterolson/BigInteger.js/pull/222/files

**Comment by thearthouse** [comment]
@peterolson con you answer will any problem on high numbers?

**Comment by Yaffle** [comment]
@peterolson I have created a new pull request, please look - https://github.com/peterolson/BigInteger.js/pull/223/files

**Comment by peterolson** [comment]
Fixed with #223.
