### ISSUE TITLE
32b and 64b constants

### ISSUE THREAD

**Issue by Rudxain** [peterolson/BigInteger.js#233]
Having constants for the maximum and minimum 32bit and 64bit values is useful, especially for bit-masking, and clamping

**Comment by peterolson** [comment]
Out of scope for this library. Since this allows integers of arbitrary size, there is nothing particularly special about 32-bit or 64-bit numbers, compared to, say, 64-bit numbers or 128-bit numbers.

These values should be easy enough to define in your own code.

**Comment by Rudxain** [comment]
What about having a function to generate an n-bit Mersenne number? Doing `bigInt.one.shiftLeft(n).prev()` or `bigInt.minusOne.shiftLeft(n).not()` is more cumbersome than `bigInt.mersenne(n)`

**Comment by Rudxain** [comment]
Fair enough
