### ISSUE TITLE
Alphabet on .toString()

### ISSUE THREAD

**Issue by doriandrn** [peterolson/BigInteger.js#242]
Hello,

I've been having a bug in my app for so long and I think I've just figured it out why it is happening.

.toString(radix, alphabet) works all right in my test cases with all radixes and different alphabets, yet it just doesn't when using 10 for radix and an alphabet.

`bigInt(5).toString(10, 'ABCDEFGHIJKLMNOP')` returns '5' which is not to be found in the alphabet requested.

**Comment by peterolson** [comment]
fixed in version 1.6.52

**Comment by doriandrn** [comment]
Thank you!
