### ISSUE TITLE
Checking if variable is instanceof BigInteger

### ISSUE THREAD

**Issue by wallverb** [peterolson/BigInteger.js#25]
Hi,

I need to check if given variable is instance of BigInteger.
I guess right now its impossible to do it in "nice" way because BigInteger is "hidden" via fnReturn.

Right now i'm doing the following: `bigInt('1234') instanceof bigInt().constructor` but it's not very elegant to create BigInteger object to perform the check

If we could add at least:
`fnReturn.isInstance = function(val)  { return val instanceof BigInteger};`

this way one could perform the check

Thanks

**Comment by peterolson** [comment]
I'll consider adding an `isInstance` function.

For now, if you don't want to create a big integer for this you can use e.g. `bigInt.one.constructor`.

**Comment by wallverb** [comment]
thanks, good idea with bigInt.one.constructor :)

**Comment by peterolson** [comment]
Sorry for the delay, I finally decided to add in an `isInstance` function.
