### ISSUE TITLE
Is it possible to get a natural log on a bigInt instance?

### ISSUE THREAD

**Issue by mikemaccana** [peterolson/BigInteger.js#26]
Hi there! I notice there's no `log()` function in the docs. is it possible to get a natural log on a bigInt instance?

**Comment by mikemaccana** [comment]
Added it: https://github.com/peterolson/BigInteger.js/pull/27

**Comment by peterolson** [comment]
This function returns a native JavaScript (floating point) number, which is unexpected in a big integer library because
 - the result is not usually an integer
 - the result cannot be arbitrarily large

Similar to the `Math.exp` function, this seems to be outside the scope of a big integer library. Do you have any examples of other integer libraries providing such a function?

**Comment by mikemaccana** [comment]
Of course, that would break chaining. I see your point. I was really looking for a good mechanism to handle log() for big numbers but I do see your point. Perhaps a stand alone function outside this library would be considered more appropriate.

**Comment by luisguillermobultetibles** [comment]
// Función logaritmo natural, take a look, please indent, the problem is the adjust at the end but it works fine, and exact. Bultet.
				// Bien, ten presente, puede que quede mejor: { Log.N(X) := Log.2(X) / Log.2(N) } no lo he probado, yet.
				Function Logarithm(a : Bigint) : Bigint; Overload;
				Var
				PA, SA : Bigint;
				Begin
				If (a = Zero) Or (a = One) Then Result := Zero Else
				If (a = Two) Then Result := One Else
				If MenorQue(a, IntToStr(Maxint)) Then
				Result := IntToStr(Trunc(Ln(StrToInt(a))))
				Else
				Begin
				PA := IntToStr(Trunc((Length(a) - 1)/Log10(Exp(1))));
				SA := Logarithm(Divide(a, Exponent(PA)));
				Result := Sumar(PA, SA)
				End;
				// Ajuste
				While MenorQue(Exponent(Sumar(Result, One)), a) Do Increment(Result);
				End;
