### ISSUE TITLE
can i initiate it from DataView

### ISSUE THREAD

**Issue by msauruv** [peterolson/BigInteger.js#34]
I am using an http API which response type is ArrayBuffer . so i am using Dataview to read int from it. now javascript support 32 bit int which is 4-byte. cane i initiate big integer with data view specifying startingOffset and length ?

**Comment by peterolson** [comment]
There's nothing built in to BigInteger.js for this, you'll have to create a function to read in the integer, maybe something like this would work:

    function convertDataToBigInt(dataView, offset, length) {
      var str = "";
      for(var i = 0; i < length; i++) {
        str += dataView.getUint32().toString(16);
      }
      return bigInt(str, 16);
    }

**Comment by msauruv** [comment]
thanks
