### ISSUE TITLE
bigInt(1) + bigInt(1) === '11'

### ISSUE THREAD

**Issue by fenivana** [peterolson/BigInteger.js#37]
Just updated to 1.5.1.

**Comment by peterolson** [comment]
Thanks, the issue should be fixed now. Let me know if the problem persists.

**Comment by Yaffle** [comment]
but `+` should not be used here...
`bigInt(1).add(bigInt(1))` is much better

**Comment by peterolson** [comment]
Sure, but this was a valid bug, since the `SmallInteger.prototype.valueOf` was not being overloaded.
