### ISSUE TITLE
Problen when using randbetween

### ISSUE THREAD

**Issue by pzhang29** [peterolson/BigInteger.js#40]
Hi there 

I tried to use the randBetween function like this: bigInt.randBetween("1","2e64"). However get such error. 
[app] TypeError: Cannot read property 'lesser' of undefined
<     at min (//*/big-integer/BigInteger.js:913:17)
<     at Function.randBetween (/*/node_modules/big-integer/BigInteger.js:945:19)

Is there anything wrong when I try to call this function. Please help to solve this problem.

Thanks,

**Comment by peterolson** [comment]
That's definitely a bug. I'll look into it on Monday

**Comment by peterolson** [comment]
Thanks, the issue should be fixed, let me know if any problems persist.
