### ISSUE TITLE
bigInt("-9007199254740983").add(bigInt("-9999999999999998")).toString() !== "-19007199254740981"

### ISSUE THREAD

**Issue by Yaffle** [peterolson/BigInteger.js#42]
seems, `if (isPrecise(a + BASE)) {` is incorrect, it should look like: `if (isPrecise(Math.abs(a) + BASE)) {`

https://github.com/peterolson/BigInteger.js/blob/master/BigInteger.js#L138

I think, it is better to make `addSmall` applicable with any carry within [0; MAX_INT)

**Comment by peterolson** [comment]
I've merged the pull
