### ISSUE TITLE
BigInteger ported to Haxe

### ISSUE THREAD

**Issue by fponticelli** [peterolson/BigInteger.js#45]
Hi Peter, I really want to thank you for this fantastic library!

For a while I wanted to implement something similar for [Haxe](http://haxe.org) and I tried several times. After a few failures I decided to "ad(a|o)pt" your code and now it [works perfectly](http://try.thx-lib.org/#3b4D9). The code is here:

https://github.com/fponticelli/thx.core/blob/master/src/thx/BigInt.hx
https://github.com/fponticelli/thx.core/tree/master/src/thx/bigint

The most notable aspect of this port is that it works on JS, CPP, C#, Java, Flash, Neko, PHP and Python. I just wanted to share my gratitude.

**Comment by peterolson** [comment]
Great, I'm glad this library was useful to you. I think it's nifty that you can override the arithmetic operators, which I imagine makes dealing with big integers a good deal less tedious.

I'm closing this issue, let me know if you need help with anything.

**Comment by fponticelli** [comment]
Based on that type I also built a Decimal type. It feels good to see things falling into the right places. Thanks again. Franco
