### ISSUE TITLE
modPow isn't working well ?

### ISSUE THREAD

**Issue by zarmack** [peterolson/BigInteger.js#46]
Hi,

I'm porting a SRP library to support biginteger, but I've detected an error in the modPow method.
There is bit of code that reproduces the error.

```javascript
'use strict';

var bigInt = require('big-integer');
var bignum = require('bignum');


function h(s) {
  return bigInt(s.split(/\s/).join(''), 16);
}

var test = [
  {
    g: h('02'),
    x: h('b5200337cc 3f3f926cdd dae0b2d310 29c069936a 844aff5877' +
         '9a545be89d 0abe'),
    N: h('ac6bdb4132 4a9a9bf166 de5e138958 2faf72b665 1987ee07fc' +
         '3192943db5 6050a37329 cbb4a099ed 8193e07577 67a13dd523' +
         '12ab4b0331 0dcd7f48a9 da04fd50e8 083969edb7 67b0cf6095' +
         '179a163ab3 661a05fbd5 faaae82918 a9962f0b93 b855f97993' +
         'ec975eeaa8 0d740adbf4 ff747359d0 41d5c33ea7 1d281e446b' +
         '14773bca97 b43a23fb80 1676bd207a 436c6481f1 d2b9078717' +
         '461a5b9d32 e688f87748 544523b524 b0d57d5ea7 7a2775d2ec' +
         'fa032cfbdb f52fb37861 60279004e5 7ae6af874e 7303ce5329' +
         '9ccc041c7b c308d82a56 98f3a8d0c3 8271ae35f8 e9dbfbb694' +
         'b5c803d89f 7ae435de23 6d525f5475 9b65e372fc d68ef20fa7' +
         '111f9e4aff 73'),
    k: h('5b9e8ef059 c6b32ea59f c1d322d37f 04aa30bae5 aa9003b832' +
         '1e21ddb04e 300'),
    a: h('f200000000 0000000000 0000000000 0000000000 0000000000' +
         '0000000000 0000000000 0000000000 0000000000 0000000000' +
         '0000000000 0000000000 0000000000 0000000000 0000000000' +
         '0000000000 0000000000 0000000000 0000000000 0000000000' +
         '0000000000 0000000000 0000000000 0000000000 0000000000' +
         '0000000000 0000000000 0000000000 0000000000 0000000000' +
         '0000000000 0000000000 0000000000 0000000000 0000000000' +
         '0000000000 0000000000 0000000000 0000000000 0000000000' +
         '0000000000 0000000000 0000000000 0000000000 0000000000' +
         '0000000000 0000000000 0000000000 0000000000 0000000000' +
         '000000d3d7'),
    u: h('b284aa1064 e8775150da 6b5e2147b4 7ca7df505b ed94a6f4bb' +
         '2ad873332a d732'),
    B: h('22ce5a7b9d 81277172ca a20b0f1efb 4643b3becc 5356647395' +
         '9b07b790d3 c3f08650d5 531c19ad30 ebb67bdb48 1d1d9cf61b' +
         'f272f84398 48fdda58a4 e6abc5abb2 ac496da509 8d5cbf90e2' +
         '9b4b110e4e 2c033c70af 73925fa374 57ee13ea3e 8fde4ab516' +
         'dff1c2ae8e 57a6b264fb 9db637eeea e9b5e43dfa ba9b329d3b' +
         '8770ce8988 8709e02627 0e474eef82 2436e63975 62f2847786' +
         '73a1a7bc12 b6883d1c21 fbc27ffb3d beb85efda2 79a69a1941' +
         '4969113f10 451603065f 0a01266664 5651dde44a 52f4d8de11' +
         '3e2131321d f1bf4369d2 585364f9e5 36c39a4dce 33221be57d' +
         '50ddccb438 4e3612bbfd 03a268a36e 4f7e01de65 1401e108cc' +
         '247db50392'),
    e: h('92aaf0f527 906aa5e860 1f5d707907 a03137e1b6 01e04b5a1d' +
         'eb02a981f4 be037b3982 9a27dba50f 1b27545ff2 e28729c2b7' +
         '9dcbdd32c9 d6b20d340a ffab91a626 a8075806c2 6fe39df91d' +
         '0ad979f9b2 ee8aad1bc7 83e7097407 b63bfe58d9 118b9b0b2a' +
         '7c5c4cdeba f8e9a460f4 bf6247b0da 34b760a59f ac891757dd' +
         'edcaf08eed 823b090586 c63009b2d7 40cc9f5397 be89a2c32c' +
         'dcfe6d6251 ce11e44e6e cbdd9b6d93 f30e90896d 2527564c7e' +
         'b9ff70aa91 acc0bac174 0a11cd184f fb989554ab 58117c2196' +
         'b353d70c35 6160100ef5 f4c28d19f6 e59ea2508e 8e8aac6001' +
         '497c27f362 edbafb25e0 f045bfdf9f b02db9c908 f10340a639' +
         'fe84c31b27')
  }
]

test.forEach(function(o, i, a) {

  // Starting the test with bigInt()
  var bi_step1 = o.g.modPow(o.x, o.N);
  var bi_step2 = o.B.subtract(o.k.multiply(o.g.modPow(o.x, o.N)));
  var bi_step3 = o.a.add(o.u.multiply(o.x));
  var bi_step4 = bi_step2.modPow(bi_step3, o.N);


  // Now with bignum !
  // Converting the numbers to bignum() from bigInt()
  var bn_g = bignum(o.g.toString(16), 16);
  var bn_x = bignum(o.x.toString(16), 16);
  var bn_k = bignum(o.k.toString(16), 16);
  var bn_a = bignum(o.a.toString(16), 16)
  var bn_u = bignum(o.u.toString(16), 16)
  var bn_B = bignum(o.B.toString(16), 16);
  var bn_N = bignum(o.N.toString(16), 16);

  var bn_step1 = bn_g.powm(bn_x, bn_N);
  var bn_step2 = bn_B.sub(bn_k.mul(bn_g.powm(bn_x, bn_N)));
  var bn_step3 = bn_a.add(bn_u.mul(bn_x))
  var bn_step4 = bn_step2.powm(bn_step3, bn_N)

  // Comparing the results
  if(bn_step4.toString(16) != bi_step4.toString(16)) {
    console.log();
    console.log("Step 4 result doesn't match !!!");
    console.log();
    console.log(" bigInt step4");
    console.log("--------------");
    console.log(bi_step4.toString(16));
    console.log();
    console.log(" bignum step4");
    console.log("--------------");
    console.log(bn_step4.toString(16));
    console.log();
    console.log(" expected step4");
    console.log("----------------");
    console.log(o.e.toString(16));
    console.log();
  }
});
```

Best regards,
Zarmack

**Comment by peterolson** [comment]
I'm having trouble at the moment installing and running the bignum library on my computer, could you give a more minimal example of a `bigInt` operation that returns an incorrect result? Something that looks like the following:

    var a = "...", b = "...", c = "...";
    bigInt(a).modPow(b,c)
    // returns "..."
    // expected "..."

**Comment by zarmack** [comment]
Hi peterolson,
Here is the example ...

``` javascript
var a = "-29694681763448712115267303514023904033265211886910761264672576231554464098637402550663040547342726600568933793424522580102024307390684120501123145913181335140054630257537266316462992944143291789428368597319366497044735307450905133722212599357295495795914532499656994934020209866067682479620381834108247731805362251476372300643310863145482504070318221407436590709353870667746678473405580031604287313646969125892734476605404502107124001169091069970155161376239893444309019800637825991490992886756114995636568690097893351815480034167383046629554600914654853770556603406920385489591581795592966209762321826324786588707444458373503608685515834491712886834370824573830770838543360344886700981870";
var b = "119334647663227291363113405741243413916434827363146166012200067038894142816254113710841716638008805209543910927476491099816542561560345503311330152550056221240122563520612198703057065667637570340647063422988042473190059156975005813463818646696643573820202000369152615667401021816298491297653620614440782978764393137821956464627163145421579373439868081673415678986432326806001408975760610901250649711198896213496068605039486228645916762983047459546900860937537474723612261449751343757826252579432285178556676653805951590208797794400875516522254480074885052650095801006651270614765243081674516367874973021395155320563";
var c = "21766174458617435773191008891802753781907668374255538511144643224689886235383840957210909013086056401571399717235807266581649606472148410291413364152197364477180887395655483738115072677402235101762521901569820740293149529620419333266262073471054548368736039519702486226506248861060256971802984953561121442680157668000761429988222457090413873973970171927093992114751765168063614761119615476233422096442783117971236371647333871414335895773474667308967050807005509320424799678417036867928316761272274230314067548291133582479583061439577559347101961771406173684378522703483495337037655006751328447510550299250924469288819";
var e = "72324557783415787424155521118202596834933898242395886137674358852236580794269836377307287786755289962440782013831739423702014967616850758313183751932896777891669089456853771795527757996329325050996269324970201536028633484579111946278204478269805106124073503820660024439715627250378312057531479971103107712537148991421528677788413535635435770715226291273808528964474082509191820953587881465428407150420995055514194080761192776104785866884604229750694117199160680355057545631740521663782384430018469927006099212868328005800482010975321397684122860835203872900466151550540270815104453823592754896203799696226528729895";

console.log("result = " + bigInt(a).modPow(b,c).toString(10));
console.log("expected = " + e);
```

Many thanks.
Zarmack

**Comment by zarmack** [comment]
I'm looking biginteger's modPow method ...

```javascript
 BigInteger.prototype.modPow = function (exp, mod) {
        exp = parseValue(exp);
        mod = parseValue(mod);
        if (mod.isZero()) throw new Error("Cannot take modPow with modulus 0");
        var r = CACHE[1],
            base = this.mod(mod);
        if (base.isZero()) return CACHE[0];
        while (exp.isPositive()) {
            if (exp.isOdd()) r = r.multiply(base).mod(mod);
            exp = exp.divide(2);
            base = base.square().mod(mod);
        }
        return r;
    };
```

and looks like ```bignumber.modPow()``` doesn't work correctly with negative exponents.


Best Regards,
Zarmack

**Comment by peterolson** [comment]
Ok, thanks for the bug report. I'm out of town for the next few days so
I'll look early next week.

**Comment by peterolson** [comment]
Ok, thanks for the bug report. I'm out of town for the next few days so
I'll look into it early next week.

**Comment by Yaffle** [comment]
`result.add(c).toString() === e` and result is negative - seems, @zarmack expects positive result

**Comment by zarmack** [comment]
@Yaffle, MANY MANY THANKS !!!
With your fix, the srp library passed all the PiCl tests !!!

Here is the "working version" of the ```BigInteger.modPow()``` method...

``` javascript
    BigInteger.prototype.modPow = function (exp, mod) {
        exp = parseValue(exp);
        mod = parseValue(mod);

        var s = CACHE[0];

        if (mod.isZero())
          throw new Error("Cannot take modPow with modulus 0");

        var r = CACHE[1];
        var base = this.mod(mod);

      	if(exp.isOdd())
      	   r = base;

        if (base.isZero())
          return CACHE[0];

        while (exp.greater(CACHE[1])) {
          exp = exp.divide(2);
          base = base.square().mod(mod);
          if (exp.isOdd())
            r = r.multiply(base).mod(mod);
        }

        // @Yaffle fix !!!!
        if(! r.isPositive())
          r = r.add(mod);

        return r;
    };
```

**Comment by fponticelli** [comment]
In the code snipped above `var s = CACHE[0];` is never used

**Comment by zarmack** [comment]
@fponticelli yes ... I've forgot erase the line !
Thanks.

**Comment by peterolson** [comment]
I'm not convinced that this is a bug, rather than by-design. This behavior follows from the behavior of the `mod` method (emphasis added):

> Performs division and returns the remainder, disregarding the quotient. **The sign of the remainder will match the sign of the dividend.**

This matches the behavior of the native JavaScript `%` operator. For example,

    -5 % 2 // -1
    bigInt(-5).mod(2) // also -1

Similarly,

    Math.pow(-5, 3) % 2 // -1
    bigInt(-5).modPow(3,2) // also -1

Maybe the `remainder` and `mod` functions should be de-unified, where `remainder` keeps the current behavior and `mod` (and consequently `modPow`) always return a non-negative result, like the Java BigInteger library does, but I'm a little hesitant to do this since it would be a breaking change, and it could be confusing for people who expect `mod` to match the JavaScript `%` modulo operator behavior. What are your thoughts?

**Comment by zarmack** [comment]
Hi Peter,

I don't know if it's a bug, but I'm sure other libraries gives a diferent result for the ```BigInteger's modPow()``` For now, I've tested [Tom Wu's jsbn](http://www-cs-students.stanford.edu/~tjw/jsbn/), [node-bignum](https://github.com/justmoon/node-bignum), and some others and all give the same output that differs from BigInteger result.

When I make the [node-srp](https://github.com/mozilla/node-srp) test with you library, on the PiCl section, only one of the tests is passed. But with other libraries all of them are pased. [BN from OpenSSL](https://www.openssl.org/docs/manmaster/crypto/bn.html) also outputs diferent than BigInteger.

I'm no mathematician, I do not know which is the correct result, what I know is that the result of BigInteger is different from all other libraries I've tested.

Regards,
Zarmack

**Comment by peterolson** [comment]
As a counterexample, [SilentMatt's library](http://silentmatt.com/biginteger/) has the same behavior as this library:

    BigInteger.parse("-5").modPow(BigInteger.small[3], BigInteger.small[2]).toString()
    // "-1"

That said, you are correct that most libraries that have have a `modPow` method seem to use the remainder from Euclidean division.

The "correct result" is ultimately subjective, I'm afraid; [different programming languages don't agree on how to do the modulo operation](https://en.wikipedia.org/wiki/Modulo_operation#Remainder_calculation_for_the_modulo_operation). Since this is a JavaScript library, I've chosen to match the behavior of JavaScript, which has the benefits of 

 - making the behavior of the library and the surrounding language consistent
 - slightly improving performance in the `mod` method for small integers because it can take advantage of the native operator without modification

Authors of some different libraries have made different choices on this point, and I certainly wouldn't say they're doing anything wrong because of that, maybe it's even a better design decision, but I don't see a rationale for it yet that's compelling enough to make a breaking change in the library. I will keep thinking about this and am open to input from anybody who has additional insight.

For now, if you want to use this library and also use `modPow` with Euclidean division, you can create a function for it:

    function EuclideanModPow(a, b, m) {
      var x = bigInt(a).modPow(b, m);
      return x.isNegative() ? x.add(m) : x;
    }

**Comment by zarmack** [comment]
Hi Peter,
Thank you very much for the solution !
Best Regards,
Zarmack

**Comment by phouse512** [comment]
@peterolson I agree with your design decision for this library, but I wonder if it's worth making a note somewhere more visible on the README about this behavior. I was working on a polyglot project that had subtle compatibility issues because of this behavior, and it took quite a while to narrow it down.

**Comment by peterolson** [comment]
Sure, go ahead and make a pull request for an update to the README
