### ISSUE TITLE
bigInt("10000000010000000").subtract(bigInt("10000000")).toString() !== "10000000000000000"

### ISSUE THREAD

**Issue by mizar** [peterolson/BigInteger.js#54]
> bigInt("10000000010000000").subtract(bigInt("10000000")).toString()
    < "100000000010000000"

https://github.com/peterolson/BigInteger.js/blob/73d1188a9fd93803f696063e2750c010e294b9cf/BigInteger.js#L191

It seems conditions are wrong.

**Comment by Yaffle** [comment]
// difference  === -10000000;
// base === 10000000;
difference % base + base // -10000000 % 10000000 + 10000000 = -0 + 10000000 = 10000000`

**Comment by peterolson** [comment]
Thanks, this should be fixed now. Let me know if any problems persist.

**Comment by deanm** [comment]
I was using 31dfff03717d7c330f2f6f719933e529198ce885, didn't see the update, thanks
