### ISSUE TITLE
randBetween broken

### ISSUE THREAD

**Issue by gpyh** [peterolson/BigInteger.js#60]
Try this: 

    bigInt.randBetween(0,"11703780079612452")

Around half of the times, you'll get `undefined`. Otherwise it works fine.

If you do this:

    bigInt.randBetween(1,"11703780079612452")

It's the same thing but instead of undefined you get ones.

I didn't thoroughly test other values, although I've been using it apparently flawlessly in other conditions where I would use other ranges. The result is the same whether I give the range a bigInt object or a String.

**Comment by peterolson** [comment]
Thanks for the bug report. This should be fixed now. Let me know if any problems persist.

**Comment by gpyh** [comment]
Works like a charm now. Thanks a lot.
