### ISSUE TITLE
root (with arbitrary radix) method would be nice...

### ISSUE THREAD

**Issue by davidedc** [peterolson/BigInteger.js#73]
e.g. ```bigInt(64).root(3) // 4```.

One would think that "pow" would be enough (inverting the radix), but actually no, because ```bigInt(64).root(1/3) // 3```, I assume because of rounding error since ```bigInt(64).pow(1/3 + 0.0000000000000001) // 4```

**Comment by davidedc** [comment]
I've given a sample draft implementation here (based on EigenMath's port I'm doing which I've been given MIT-license permission by the original EigenMath author) https://github.com/davidedc/EigenCoffeeMath/blob/master/mroot.coffee

Passes my tests at the end of the file e.g.

```mroot(mpow(bigInt(12345),23),23)``` (where mpow if the standard bigInt pow implementation) i.e.
```mpow(bigInt(12345),23) === bigInt("12714379441807215864085530676173437635691005317036328268339441367581058492804872989654541015625")```

**Comment by davidedc** [comment]
(p.s. it's in coffeescript but there is a coffeescript to JS translator here http://coffeescript.org/ )

**Comment by peterolson** [comment]
This method seems out of scope for a bigInt library. What should the `root` method return?

 - a `bigInt`? No, because `bigInt(17).root(2)`, for example, would not be an integer. In fact, most of the time the result could not be represented as an integer.
 - a native JavaScript number? No, because the result is possibly too large to fit in a native JavaScript number.
 - a [BigRational](https://github.com/peterolson/BigRational.js)? No, because roots are usually irrational.
 - throw an error if there is no perfect root? Then the set of acceptable inputs is rather small, and I don't see the method being that useful in this case - if you already know a number has a perfect root, then you are already half-way to knowing what the root is.

**Comment by davidedc** [comment]
Yep, as the description in the implementation I linked, it returns the bigint root if the passed number has a perfect root. If not, error/null.

Such a thing is indeed useful in computer algebra systems to simplify numbers under roots if possible (i.e. "calculate the roots away" if they are perfect).

Fair enough if this is out of scope of bigInt. For whoever ends up in here via a search: look the link above or get in touch with me.

**Comment by Yaffle** [comment]
```
// A**(1/n)
bigInt.nthRoot = function (A, n) { // bugs - ?
  var integerLogarithm = function (value, base) {
    if (base.compareTo(value) <= 0) {
      var tmp = integerLogarithm(value, base.square(base));
      var p = tmp.p;
      var e = tmp.e;
      var t = p.multiply(base);
      return t.compareTo(value) <= 0 ? {p: t, e: e.add(e).add(bigInt(1))} : {p: p, e: e.add(e)};
    }
    return {p: bigInt(1), e: bigInt(0)};
  };
  // https://stackoverflow.com/questions/15978781/how-to-find-integer-nth-roots
  var nthRoot = function (A, n, e) {
    if (e.compareTo(n) < 0) {
      return bigInt(1);
    }
    var q = e.divide(n).divide(bigInt(2));
    var t = bigInt(2).pow(q);
    var x0 = q.compareTo(bigInt(0)) === 0 ? bigInt(4) : t.add(bigInt(1)).multiply(nthRoot(A.divide(t.pow(n)), n, e.subtract(q.multiply(n))));
    var x = x0;
    var xp = x.add(bigInt(1));
    while (x.compareTo(xp) < 0) {
      xp = x;
      var t = A.divide(x.pow(n.subtract(bigInt(1))));
      x = x.multiply(n.subtract(bigInt(1))).add(t).divide(n);
    }
    return xp;
  };
  A = bigInt(A);
  n = bigInt(n);
  if (A.compareTo(bigInt(0)) < 0 || n.compareTo(bigInt(0)) <= 0) {
    throw new RangeError();
  }
  if (A.compareTo(bigInt(0)) === 0) {
    return bigInt(0);
  }
  var e = integerLogarithm(A, bigInt(2)).e;
  var x = nthRoot(A, n, e);
  return x;
};
```
