### ISSUE TITLE
XOR issue

### ISSUE THREAD

**Issue by cmitch13** [peterolson/BigInteger.js#75]
I'm using this library for a hashing function, more precisely I'm using the xor and times functions within this library. However, precision seems to be an issue.

With this library:
-3750763034362895579 XOR 52 = -3750763034362895400

Correct answer:
-3750763034362895579 XOR 52 = -3750763034362895599

**Comment by peterolson** [comment]
Can you post the code you are using? I cannot reproduce the issue. The following code:

    bigInt("-3750763034362895579").xor(52).toString()

returns the correct answer:

    "-3750763034362895599"

**Comment by cmitch13** [comment]
function testHash() {
	var init = bigInt("-3750763034362895579",10);
	var prime = bigInt("1099511628211",10);
	
	var hash = init;
	var inputBytes = [52, 48, 55, 118, 86, 52, 85, 86, 106, 57, 67, 121, 68, 65];
	for(var i = 0; i < inputBytes.length; i++) {
		hash = hash.xor(inputBytes[i]);
		if(i == 0) {
			//just printing known example from previous question
			console.log("-3750763034362895579 XOR 52 = -3750763034362895599");
			console.log("actual XOR result: " + hash);
		}
		hash = hash.times(prime);
	}
	
	console.log("actual: " + hash);
	console.log("expected: 8401341548799639795");
}

**Comment by peterolson** [comment]
This line will print imprecise results

    console.log("actual XOR result: " + hash);

because the `+` operator will cause the `valueOf` method to be called, which will convert `hash` into a native JavaScript number, which cannot accurately represent larger values.

You can print the precise string representation using the `String` function or the `toString` method:

    console.log("actual XOR result: " + String(hash));
    console.log("actual XOR result: " + hash.toString());

Let me know if you have any further questions.

**Comment by cmitch13** [comment]
I'm having problems converting hex to decimal when the value is negative.  Check out my fiddle here: https://jsfiddle.net/cqepbvyh/.

**Comment by peterolson** [comment]
It seems you are wanting to convert the hex number `e7bab700ba933e88` into decimal, yes?

`bigInt('e7bab700ba933e88', 16).toString()` correctly outputs `"16697859782187630216"`. ([You can verify the result on Wolfram Alpha](http://www.wolframalpha.com/input/?i=e7bab700ba933e88_16+to+decimal)) I'm not sure where your expected value of `-1748884291521921400` comes from.

**Comment by cmitch13** [comment]
I have checked with Windows calculator and Google BigQuery.  Both return the result -1748884291521921400.

![hex-dec-conversion-calculator](https://cloud.githubusercontent.com/assets/17030247/14337311/8aed8dea-fc21-11e5-9b1c-93fbcd8afd4a.png)
![hex-dec-conversion-gbq](https://cloud.githubusercontent.com/assets/17030247/14337317/933fe218-fc21-11e5-9e16-5e465590b248.PNG)

**Comment by peterolson** [comment]
OK, I see what you mean. Yes, `0xe7bab700ba933e88` in a fixed 64-bit two's-complement representation is indeed `-1748884291521921400`. BigInteger represents arbitrarily large integers, potentially larger than 64-bits, so it doesn't make sense to use two's complement. Instead, it uses a minus sign to represent negative integers.

**Comment by cmitch13** [comment]
With bigInt, if I know the input is fixed 64-bit two's-complement representation, is there a way to get from e7bab700ba933e88 to -1748884291521921400?

**Comment by peterolson** [comment]
Sure, you can write a function to do the conversion:

```
function toTwosComplement(n) {
    n = bigInt(n, 16);
    var minInt = bigInt("8000000000000000", 16);
    var isNegative = minInt.and(n).isPositive();
    return isNegative ? minInt.negate().add(n.xor(minInt)) : n;
}
```

Then you can do this:

    > toTwosComplement("e7bab700ba933e88").toString()
    "-1748884291521921400"
