### ISSUE TITLE
sqrt

### ISSUE THREAD

**Issue by lionvs** [peterolson/BigInteger.js#77]
Is there some specific reason why square root method isn't implemented?

**Comment by peterolson** [comment]
Yes. Most of the time the square root operation does not return an integer, whereas the methods in a big integer library should return integers. I do not know of any other big integer library which includes the square root method.

For example, what should `bigInt(5).sqrt()` return?

**Comment by nickkolok** [comment]
> For example, what should `bigInt(5).sqrt()` return?

IMO, it should return 2, as `bigInt(4).sqrt()`. `x.sqrt()` should return the biggest value `y` such as `y*y<=x`.

It is really necessary in number theory (the classical example is factorization of a number). On the other hand. numbertheory is a significant part of aim area of `BigInteger`s.

**Comment by Yaffle** [comment]
see https://github.com/peterolson/BigInteger.js/issues/73#issuecomment-351155110 for an implementation of `nthRoot`
