### ISSUE TITLE
Bower package please :)

### ISSUE THREAD

**Issue by volkovasystems** [peterolson/BigInteger.js#78]
Can we have a bower package for this please <3

**Comment by peterolson** [comment]
Hi, Sorry for the delay in responding to you. I haven't used bower before, so I don't know much about using or releasing bower packages. From skimming through the docs, it seems you can use bower to install a script from its URL, like this:

    bower install http://peterolson.github.com/BigInteger.js/BigInteger.min.js

Does this not work? Is there some benefit to creating a package?

**Comment by volkovasystems** [comment]
Thanks for the reply!

Yes, there's a benefit from the perspective that you can use a simple namespace like "big-integer" if I'm going to do what you just suggested, I will still need to do this, 

`bower install big-integer=<file> --save`

So that it will register to my bower.json with a simple namespace and it will be easier to uninstall later on that I can just 

`bower uninstall big-integer`

So if you register this to bower, which I think a great module than others (since I've used one before but there are limitations and yours is better), we can get these simple benefits. Plus you own the bower module :smile:

**Comment by peterolson** [comment]
I added a bower.json file. It seems that the bower package `big-integer` pointing to this repository already exists. Can you confirm that `bower install big-integer` works as expected?

**Comment by volkovasystems** [comment]
Sorry for the delayed reply, yes this is working properly thank you so much!
