### ISSUE TITLE
Add built-in secure random number genoration.

### ISSUE THREAD

**Issue by AppIns** [peterolson/BigInteger.js#79]
I was wondering if you could add adding built-in secure random number generation. Possibly using window.crypto.getRandomValues for browsers and require('crypto') for node.js. Thanks!

**Comment by peterolson** [comment]
Sorry for the late reply. I'm afraid that this, along with a myriad of other cryptographic features, is out of scope of this library. Currently there are no dependencies, and I'm reluctant to add one for a relatively minor feature, and I am not qualified to implement secure random number generation myself.

Anyways, it should be fairly straightforward for BigInteger.js to use data generated by [`crypto.getRandomBytes`](https://nodejs.org/api/crypto.html#crypto_crypto_randombytes_size_callback).  If you have trouble with this, let me know and I'll be happy to help.
