### ISSUE TITLE
modInv shall throw if no inverse is found

### ISSUE THREAD

**Issue by Marandil** [peterolson/BigInteger.js#82]
The modInv function is implemented using Extended Euclidean Algorithm, which is a straightforward function, but requires does behave normally, even if `this` is not co-prime to the modulus `n`. In such a case, the resulting `t` is not a proper inversion modulo, as such number does not exist (i.e. there is no number `t` s.t. `t*a - k*n = 1` for any k).
In order to address the issue, implementations usually check during the algorithm whether `gcd(this,n) == 1` by checking the value of `r`, as it indicates the `gcd` in EEA.
The easy, one-liner fix for the issue is to check it as well:
```javascript
if(!r.equals(1)) throw new Error(this.toString() + " and " + n.toString() + " are not co-prime");
```
The line shall be added anywhere between the end of the `while` loop and the `return t` statement.

**Comment by peterolson** [comment]
Thanks a lot. I've implemented the change you suggested.
