### ISSUE TITLE
Bower version

### ISSUE THREAD

**Issue by dennislaumen** [peterolson/BigInteger.js#83]
Hi,

The bower support, as requested in https://github.com/peterolson/BigInteger.js/issues/78, works! 

Unfortunately I am not able to specify a version number. This means I cannot use a "release" of _big-integer_ but either have to build with the latest commit, which might mean my builds might unexpectedly break in the future, or depend on a git commit hash, which makes it difficult and error-prone to depend on the correct version.

While reading the bower [docs](https://bower.io/docs/creating-packages/) (I'm not an expert on creating packages) it seems that all that is required is pushing semver git tags. Would it be possible to add a 1.6.17 git tag to the latest release and use git tags to tag future versions?

I would love to send you a pull request but I don't think one can make PRs for git tags. Please let me know if there is anything I can do to make this happen.

Thanks for all the great work on this library! ❤️

Regards,

Dennis

**Comment by peterolson** [comment]
Thanks for the suggestion. I had actually been meaning to add git tags for a while, this was a good reminder.

I just added tags for all version from 1.6.0 and up. Let me know if that resolves your issue.

**Comment by dennislaumen** [comment]
Works like a charm, thanks @peterolson!

```
$ bower install big-integer@1.6.17
bower not-cached    https://github.com/peterolson/BigInteger.js.git#1.6.17
bower resolve       https://github.com/peterolson/BigInteger.js.git#1.6.17
bower download      https://github.com/peterolson/BigInteger.js/archive/v1.6.17.tar.gz
bower extract       big-integer#1.6.17 archive.tar.gz
bower resolved      https://github.com/peterolson/BigInteger.js.git#1.6.17
bower install       big-integer#1.6.17

big-integer#1.6.17 bower_components/big-integer
```
