### ISSUE TITLE
Division gives wrong answers

### ISSUE THREAD

**Issue by russellw** [peterolson/BigInteger.js#88]
var bi=require('big-integer')
var a=bi('1e9999')
var b=bi('1e999')
b=a.divide(b)
console.log(b.toString())

The output contains lots of 8s and 9s; something wrong in the division algorithm? This might be the cause of the bug I reported a few minutes ago in big-rational?

**Comment by Yaffle** [comment]
Seems, "compareAbs" returns wrong result, as "part" is not "trimmed" (all zeros).

```
         while (a_l) {
-             part.unshift(a[--a_l]);
+            var higha = a[--a_l];
+            if (part.length !== 0 || higha !== 0) {
+              part.unshift(higha);
+            }
             if (compareAbs(part, b) < 0) {
                 result.push(0);
                 continue;
             }
```

**Comment by peterolson** [comment]
Thanks for the issue report, and thank @Yaffle for identifying the issue. This should be fixed now.
