### ISSUE TITLE
Construct from an array

### ISSUE THREAD

**Issue by polkovnikov-ph** [peterolson/BigInteger.js#89]
Some strings are using bases higher than 10. (In my personal use case it's 256.) Could you add an option to create a big integer from an array, please?

**Comment by peterolson** [comment]
BigInteger supports bases higher than 10 with a second argument specifying the base. You can use the letters a-z for digits from 11-36, and you can also enclose digits in angle brackets:

    bigInt("<255>0", 256) 

Which is equivalent to 0xff00

**Comment by polkovnikov-ph** [comment]
@peterolson That's the approach I've used, but it makes no sense to serialize an array to a string just to parse it the exact next moment.

**Comment by Yaffle** [comment]
@polkovnikov-ph  for this particular case you could try to convert your string to a hex string as the conversion from 256 to 16 is "simple", and then use the `bigInt`.

**Comment by polkovnikov-ph** [comment]
@Yaffle It doesn't really matter if it's simple or not. It takes time to implement and to run.

**Comment by peterolson** [comment]
The array will already have to be converted into a string behind the scenes to pass into the base conversion function, so as far as performance is concerned there wouldn't be any benefit - passing in an array would actually be adding an extra step, not removing one. 

I can see the benefit for user convenience, but I'm not yet convinced that this is a common enough use case to be worth baking into the library.

**Comment by polkovnikov-ph** [comment]
@peterolson Why base conversion function deals with strings? This is a numeric task.

**Comment by peterolson** [comment]
I've added the [`fromArray` static method.](https://github.com/peterolson/BigInteger.js/tree/master#fromarraydigits-base--10-isnegative) Let me know if this resolves your issue.

**Comment by polkovnikov-ph** [comment]
@peterolson Great!

I've found several issue, though:
1. In `parseBaseFromArray` variable `i` is not defined.
2. This commit makes a call to `parseBase` a bit slower (but people generally shouldn't care about that if they're parsing from string).
3. In `digits.push(parseValue(c.charCodeAt(0) - 87));` it's possible to use `charCode` variable.
4. `isNegative ? 1 : 0` is just `+isNegative` and has a lower chance to reset CPU pipeline this way.

Probably I should take a look on the whole source code.
