### ISSUE TITLE
Tag the latest npm release

### ISSUE THREAD

**Issue by jaredwy** [peterolson/BigInteger.js#91]
It appears that bower attempts to parse the tags to find the latest version to install. Would you be able to create a tag for the last npm release `1.6.22` so bower can pick it up

Thanks!

**Comment by peterolson** [comment]
Sure, sorry I've forgotten to do that for the last few releases. I'll try to remember in the future.

**Comment by jaredwy** [comment]
No problem! thanks heaps.
