### ISSUE TITLE
Adding TypeScript definitions

### ISSUE THREAD

**Issue by toefraz** [peterolson/BigInteger.js#93]
Hi, would you be interested in adding a TypeScript definition file to your repository?

There's a community-created definition file hosted in the DefinitelyTyped registry [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/big-integer/index.d.ts), but it frequently gets out of sync with your library. I think having an official definition file directly in your repo would make it easier to tell when things have changed to keep it up-to-date, and would eliminate having to depend on a second package when using big-integer in TypeScript.

I use your library all the time, and this would definitely make my life easier. I would be more than willing to create a PR for it and update it when needed if you're willing to host it here.

**Comment by peterolson** [comment]
Sure, that'd be great. If you make a pull request for TypeScript definitions I'll definitely pull it in and take a look at it.

**Comment by toefraz** [comment]
Awesome! I'll work on it. Maybe expect a PR this weekend 👍
