### ISSUE TITLE
Access internal array presentation of number

### ISSUE THREAD

**Issue by piu130** [peterolson/BigInteger.js#98]
I don't know if I'm correct but I think you represent the numbers as array ([Int8Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array)/[UInt8Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array)).

It would be nice if you create a getter/setter/constructor for this array to use it with a [NodeJS buffer](https://nodejs.org/api/buffer.html).

Otherwise we must convert the buffer to a string and pass this to your constructor, where it's parsed back to an array.

**Comment by peterolson** [comment]
Actually it's stored internally as an `Array` of `Number`s in base `10000000`, rather than a `UInt8Array` in base 256.

There is a [`fromArray`](https://github.com/peterolson/BigInteger.js#fromarraydigits-base--10-isnegative) method for constructing bigIntegers that might work for your purposes.
